#    _____                      _______ _
#  / ____|                     |__   __(_)
# | (___   ___ _ ____   _____ _ __| |   _ _ __ ___   ___
#  \___ \ / _ \ '__\ \ / / _ \ '__| |  | | '_ ` _ \ / _ \
#  ____) |  __/ |   \ V /  __/ |  | |  | | | | | | |  __/
# |_____/ \___|_|    \_/ \___|_|  |_|  |_|_| |_| |_|\___|
#
# Version 1.0
configVersion: 1

Worlds:
  - "world"

Time:
  Month: 1
  Day: 1
  WeekDay: 1
  Hour: 0
  Minute: 0

TimeSlot:
  1:
    name: "Midnight"
    start:
      hour: 0
      minute: 0
    end:
      hour: 5
      minute: 0
    weekdays:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7